import { Center, Heading } from '@chakra-ui/layout';
import Head from 'next/head';

import Layout from '../layouts/Layout';

const Home: React.FC = () => {
  return (
    <Layout fullHeight>
      <Head>
        <title>NextJS Typescript Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center h="full">
        <Heading fontSize="120px">🍻</Heading>
      </Center>
    </Layout>
  );
};

export default Home;
