import { Box } from '@chakra-ui/layout';
import Head from 'next/head';

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main">Hello there, Kenobi!</Box>

      <Box as="footer">Footer!</Box>
    </div>
  );
};

export default Home;
