import { Flex, Heading } from '@chakra-ui/layout';
import Head from 'next/head';

import Layout from '../components/Layout';

const Home: React.FC = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex h="full" bg="cyan.500" alignItems="center" justifyContent="center">
        <Heading>Hello there, Kenobi!</Heading>
      </Flex>
    </Layout>
  );
};

export default Home;
